#!/bin/bash

CONTAINER=mpc
IMAGE=mpc
VOLUME=$(readlink $(pwd))
CONFIG="${VOLUME}/config"
echo Config directory: $CONFIG
mkdir -p $CONFIG
hostname=$(hostname)
DOMAIN=${hostname#*.*}

pushd $IMAGE
  if [ ! -f java.tgz ]
  then
    docker run -i -t --rm -v `pwd`:/export docker.io/store/oracle/serverjre:8 tar -zchf /export/java.tgz /usr/java/latest
  fi
  if [ ! -f java.tgz ]
  then
    echo This requires that have accepted the java license and that docker is logged in.
    echo Please see https://hub.docker.com/_/oracle-serverjre-8 for details.
    echo Thi unfortunaly means you have to build you own image as this cannot be build on docker hub.
  fi
  docker build . -t $IMAGE || exit 1 
popd

# kill any running containers
docker stop $CONTAINER > /dev/null 2>&1
docker rm   $CONTAINER > /dev/null 2>&1
ID=$( \
 docker run -d \
  -d \
  -p 8080 \
  -e "VIRTUAL_HOST=$CONTAINER.$DOMAIN" \
  -e "VIRTUAL_PORT=8080" \
  -v ${CONFIG}:/config \
  -e EDGE=0 \
  -e USER_ID=1000 \
  -e GROUP_ID=1000 \
  --name $CONTAINER \
  --restart always \
  -t $IMAGE \
 )
echo $CONTAINER container: $ID
