#!/bin/bash

CONTAINER=mpc
IMAGE=hall757/raritan-mpc
VOLUME=$(readlink $(pwd))
CONFIG="${VOLUME}/config"
echo Config directory: $CONFIG
mkdir -p $CONFIG
hostname=$(hostname)
DOMAIN=${hostname#*.*}
echo dockergen-nginx will use $CONTAINER.$DOMAIN as the virtual host name.

pushd mpc
  if [ ! -f java.tgz ]
  then
    docker run -i -t --rm -v `pwd`:/export docker.io/store/oracle/serverjre:8 tar -zchf /export/java.tgz /usr/java/latest
  fi
  if [ ! -f java.tgz ]
  then
    echo This requires that have accepted the java license and that docker is logged in.
    echo Please see https://hub.docker.com/_/oracle-serverjre-8 for details.
    echo Thi unfortunaly means you have to build you own image as this cannot be build on docker hub.
  fi
  sudo docker build . -t $IMAGE || exit 1 
popd

# kill any running containers
sudo docker stop $CONTAINER > /dev/null 2>&1
sudo docker rm   $CONTAINER > /dev/null 2>&1
cmd=$( echo \
 sudo docker run -d \
  -p 8080 \
  -h CONTAINER \
  -e "VIRTUAL_HOST=$CONTAINER.$DOMAIN" \
  -e "VIRTUAL_PORT=8080" \
  -v ${CONFIG}:/config \
  --name $CONTAINER \
  --restart always \
  -t $IMAGE \
 )
echo $cmd
ID=$($cmd)

echo $CONTAINER container: $ID
